export interface FlowerModelInfo {
  id: string;
  file: string;
  name: string;
  category: 'bouquet' | 'rose' | 'vase' | 'lotus' | 'sakura' | 'peony' | 'fantasy';
  categoryLabel: string;
  tagline: string;
  defaultMessage: string;
  accentColor: string;
  glowColor: string;
  targetScale?: number;
  cameraDistance?: number;
}

export const FLOWER_MODELS: FlowerModelInfo[] = [
  // ── 💐 精选手捧花束 (Bouquets) ───────────────────────────
  {
    id: 'bouquet',
    file: 'bouquet.glb',
    name: '典雅手捧花束',
    category: 'bouquet',
    categoryLabel: '手捧花束',
    tagline: '把世间所有美好，都捧到你面前',
    defaultMessage: '为你捧来一束不凋零的繁花，愿幸福常伴你左右。',
    accentColor: '#ec4899',
    glowColor: '#fbcfe8',
    targetScale: 2.3,
    cameraDistance: 4.5
  },
  {
    id: 'flower_bouquet',
    file: 'flower_bouquet.glb',
    name: '繁花似锦礼束',
    category: 'bouquet',
    categoryLabel: '手捧花束',
    tagline: '春风和煦，繁花盛放',
    defaultMessage: '愿生活如这繁花般绚烂多彩，愿你被这世间所有善意温柔以待。',
    accentColor: '#f59e0b',
    glowColor: '#fef08a',
    targetScale: 2.2,
    cameraDistance: 4.8
  },
  {
    id: 'wrapped_flower_bouquet',
    file: 'wrapped_flower_bouquet.glb',
    name: '丝带礼品花束',
    category: 'bouquet',
    categoryLabel: '手捧花束',
    tagline: '精心包装的每一瓣，皆是心意',
    defaultMessage: '系上一缕温柔的丝带，送给独一无二的你。',
    accentColor: '#fb7185',
    glowColor: '#ffe4e6',
    targetScale: 2.4,
    cameraDistance: 5.0
  },
  {
    id: 'a_bouquet_of_flowers',
    file: 'a_bouquet_of_flowers.glb',
    name: '温情手捧花',
    category: 'bouquet',
    categoryLabel: '手捧花束',
    tagline: '手握繁花，心有阳光',
    defaultMessage: '采撷一路的花香送予你，愿你的每一天都充满芬芳与暖意。',
    accentColor: '#f43f5e',
    glowColor: '#fecdd3',
    targetScale: 2.3,
    cameraDistance: 4.6
  },
  {
    id: 'bouquet_of_flowers',
    file: 'bouquet_of_flowers.glb',
    name: '春日手捧礼束',
    category: 'bouquet',
    categoryLabel: '手捧花束',
    tagline: '满怀春意，皆赠予你',
    defaultMessage: '把整个春天的浪漫打包成束，送给最特别的你。',
    accentColor: '#fb923c',
    glowColor: '#ffedd5',
    targetScale: 2.3,
    cameraDistance: 4.6
  },
  {
    id: 'bouquet_of_flowers_alt',
    file: 'bouquet_of_flowers_alt.glb',
    name: '奢华盛典花束',
    category: 'bouquet',
    categoryLabel: '手捧花束',
    tagline: '盛大绽放，荣耀与共',
    defaultMessage: '举杯祝贺每一个值得纪念的闪耀时刻，愿你前程璀璨如花！',
    accentColor: '#e11d48',
    glowColor: '#fda4af',
    targetScale: 2.4,
    cameraDistance: 4.8
  },
  {
    id: 'flower_bouquet__kytica_kvetov',
    file: 'flower_bouquet__kytica_kvetov.glb',
    name: '欧式复古花束',
    category: 'bouquet',
    categoryLabel: '手捧花束',
    tagline: '古典优雅，经久沉香',
    defaultMessage: '如古典油画般优雅沉静，愿这份古典浪漫长驻心间。',
    accentColor: '#d97706',
    glowColor: '#fef3c7',
    targetScale: 2.3,
    cameraDistance: 4.6
  },
  {
    id: 'mixed_flower_bouquet__downloadable_3d_scan',
    file: 'mixed_flower_bouquet__downloadable_3d_scan.glb',
    name: '自然写真花束',
    category: 'bouquet',
    categoryLabel: '手捧花束',
    tagline: '宛若天成，自然之美',
    defaultMessage: '自然的芬芳无需过多修饰，愿你保有这份纯真与自在。',
    accentColor: '#10b981',
    glowColor: '#a7f3d0',
    targetScale: 2.2,
    cameraDistance: 4.4
  },
  {
    id: 'dry_flower',
    file: 'dry_flower.glb',
    name: '永生风干花束',
    category: 'bouquet',
    categoryLabel: '手捧花束',
    tagline: '岁月凝固，真情不褪',
    defaultMessage: '时间会流逝，但那些真挚的情感如永生花般永不褪色。',
    accentColor: '#d97706',
    glowColor: '#fed7aa',
    targetScale: 2.3,
    cameraDistance: 4.5
  },
  {
    id: 'flower_arrangement',
    file: 'flower_arrangement.glb',
    name: '典雅花艺组合',
    category: 'bouquet',
    categoryLabel: '手捧花束',
    tagline: '匠心插艺，层次分明',
    defaultMessage: '每一瓣的错落皆是心意，愿精致的美好点缀你的生活。',
    accentColor: '#ec4899',
    glowColor: '#fbcfe8',
    targetScale: 2.3,
    cameraDistance: 4.6
  },
  {
    id: 'flower_arrangement_alt',
    file: 'flower_arrangement_alt.glb',
    name: '华彩花艺设计',
    category: 'bouquet',
    categoryLabel: '手捧花束',
    tagline: '色彩交融，相得益彰',
    defaultMessage: '愿丰富多彩的经历如这束花艺，拼织出你璀璨充盈的人生。',
    accentColor: '#8b5cf6',
    glowColor: '#ede9fe',
    targetScale: 2.3,
    cameraDistance: 4.6
  },

  // ── 🌹 浪漫玫瑰与月季 (Roses) ─────────────────────────────
  {
    id: 'flower',
    file: 'flower.glb',
    name: '暮光蔷薇',
    category: 'rose',
    categoryLabel: '玫瑰月季',
    tagline: '满目山河，唯你最温柔',
    defaultMessage: '愿你的世界常有繁花相伴，满目皆是温柔与偏爱。',
    accentColor: '#f43f5e',
    glowColor: '#fda4af',
    targetScale: 2.2,
    cameraDistance: 4.2
  },
  {
    id: 'red_rose',
    file: 'red_rose.glb',
    name: '经典绯红玫瑰',
    category: 'rose',
    categoryLabel: '玫瑰月季',
    tagline: '热烈炽爱，至死不渝',
    defaultMessage: '这一抹绯红只为你盛开，愿爱意如烈火般纯粹永恒。',
    accentColor: '#e11d48',
    glowColor: '#fecdd3',
    targetScale: 2.2,
    cameraDistance: 4.0
  },
  {
    id: 'rose',
    file: 'rose.glb',
    name: '初绽红玫瑰',
    category: 'rose',
    categoryLabel: '玫瑰月季',
    tagline: '心之所向，怦然心动',
    defaultMessage: '每一次初绽都是心动的证明，愿所有美好如期而至。',
    accentColor: '#f43f5e',
    glowColor: '#fda4af',
    targetScale: 2.1,
    cameraDistance: 4.0
  },
  {
    id: 'single_flower__rose_pink',
    file: 'single_flower__rose_pink.glb',
    name: '娇艳粉玫瑰',
    category: 'rose',
    categoryLabel: '玫瑰月季',
    tagline: '柔情似水，浪漫心动',
    defaultMessage: '送你一朵粉色温柔，愿你的梦境常有花香与星光。',
    accentColor: '#f472b6',
    glowColor: '#fdf2f8',
    targetScale: 2.2,
    cameraDistance: 4.0
  },
  {
    id: 'single_flower__rose_blue',
    file: 'single_flower__rose_blue.glb',
    name: '梦幻蓝玫瑰',
    category: 'rose',
    categoryLabel: '玫瑰月季',
    tagline: '奇迹与不可能之爱',
    defaultMessage: '你是我生命中最奇妙的奇迹，愿深蓝带给你无限灵感。',
    accentColor: '#3b82f6',
    glowColor: '#bfdbfe',
    targetScale: 2.2,
    cameraDistance: 4.0
  },
  {
    id: 'elina_rose_2022_spring',
    file: 'elina_rose_2022_spring.glb',
    name: '埃琳娜春日月季',
    category: 'rose',
    categoryLabel: '玫瑰月季',
    tagline: '淡雅纯净，春日清风',
    defaultMessage: '如早春拂面而来的清风，愿这份纯净扫清所有疲惫。',
    accentColor: '#fef08a',
    glowColor: '#fef9c3',
    targetScale: 2.2,
    cameraDistance: 4.0
  },
  {
    id: 'peche_bonbons_rose_2022_spring',
    file: 'peche_bonbons_rose_2022_spring.glb',
    name: '蜜桃糖果玫瑰',
    category: 'rose',
    categoryLabel: '玫瑰月季',
    tagline: '甜美如果实，香气扑鼻',
    defaultMessage: '愿你的生活甜如蜜桃糖果，天天都有微甜的小确幸。',
    accentColor: '#fb923c',
    glowColor: '#ffedd5',
    targetScale: 2.2,
    cameraDistance: 4.0
  },
  {
    id: 'sharme_rose_in_2022_spring',
    file: 'sharme_rose_in_2022_spring.glb',
    name: '夏尔姆优雅玫瑰',
    category: 'rose',
    categoryLabel: '玫瑰月季',
    tagline: '端庄典雅，芬芳四溢',
    defaultMessage: '愿岁月赠予你从容与智慧，在每一个季节里优雅盛开。',
    accentColor: '#ec4899',
    glowColor: '#fbcfe8',
    targetScale: 2.2,
    cameraDistance: 4.0
  },
  {
    id: 'pale_orange_rosename_unknown',
    file: 'pale_orange_rosename_unknown.glb',
    name: '暖阳杏橙玫瑰',
    category: 'rose',
    categoryLabel: '玫瑰月季',
    tagline: '落日熔金，温暖如初',
    defaultMessage: '像傍晚最温柔的霞光，将这份温暖赠予赶路的你。',
    accentColor: '#f97316',
    glowColor: '#fed7aa',
    targetScale: 2.2,
    cameraDistance: 4.0
  },
  {
    id: 'distant_drams_rose',
    file: 'distant_drams_rose.glb',
    name: '遥远之梦玫瑰',
    category: 'rose',
    categoryLabel: '玫瑰月季',
    tagline: '梦境与远方，皆在脚下',
    defaultMessage: '勇敢追寻心中的远方，愿你的梦想终将如玫瑰般热烈盛开。',
    accentColor: '#a855f7',
    glowColor: '#f3e8ff',
    targetScale: 2.2,
    cameraDistance: 4.0
  },
  {
    id: 'roses_in_tivoli_gardens',
    file: 'roses_in_tivoli_gardens.glb',
    name: '趣伏里花园玫瑰',
    category: 'rose',
    categoryLabel: '玫瑰月季',
    tagline: '童话花园，浪漫徜徉',
    defaultMessage: '愿你拥有一座属于自己的浪漫花园，无忧无虑，自由盛开。',
    accentColor: '#e11d48',
    glowColor: '#fecdd3',
    targetScale: 2.2,
    cameraDistance: 4.0
  },

  // ── 🏺 瓷瓶插花与盆景 (Vase & Pots) ───────────────────────────
  {
    id: 'flowers_with_the_vase',
    file: 'flowers_with_the_vase.glb',
    name: '清雅瓷瓶插花',
    category: 'vase',
    categoryLabel: '瓶中繁花',
    tagline: '岁月静好，素雅芬芳',
    defaultMessage: '愿平静与美好如这瓶中繁花，悄然点缀你的每一个日常。',
    accentColor: '#a855f7',
    glowColor: '#e9d5ff',
    targetScale: 2.3,
    cameraDistance: 4.5
  },
  {
    id: 'flowers_in_pink_vase',
    file: 'flowers_in_pink_vase.glb',
    name: '粉陶馨香插花',
    category: 'vase',
    categoryLabel: '瓶中繁花',
    tagline: '温馨相伴，恬淡从容',
    defaultMessage: '给平凡的生活添一抹粉色馨香，愿你每天都有好心情。',
    accentColor: '#f472b6',
    glowColor: '#fdf2f8',
    targetScale: 2.2,
    cameraDistance: 4.2
  },
  {
    id: 'flowers_in_vase',
    file: 'flowers_in_vase.glb',
    name: '琉璃瓶中繁花',
    category: 'vase',
    categoryLabel: '瓶中繁花',
    tagline: '琉璃透光，繁花静好',
    defaultMessage: '愿你的心灵剔透澄澈，收纳世间所有美好景致。',
    accentColor: '#0ea5e9',
    glowColor: '#bae6fd',
    targetScale: 2.3,
    cameraDistance: 4.4
  },
  {
    id: 'bunch_of_flowers_with_vase',
    file: 'bunch_of_flowers_with_vase.glb',
    name: '雅致插花组合',
    category: 'vase',
    categoryLabel: '瓶中繁花',
    tagline: '高低错落，别具匠心',
    defaultMessage: '愿生活如插花般讲究而有趣，处处皆是风景。',
    accentColor: '#8b5cf6',
    glowColor: '#ddd6fe',
    targetScale: 2.3,
    cameraDistance: 4.5
  },
  {
    id: 'flowervase',
    file: 'flowervase.glb',
    name: '白瓷盛夏插花',
    category: 'vase',
    categoryLabel: '瓶中繁花',
    tagline: '白瓷素净，夏日生机',
    defaultMessage: '愿你保有夏日般的蓬勃朝气，在素净的时光里绽放光芒。',
    accentColor: '#10b981',
    glowColor: '#d1fae5',
    targetScale: 2.3,
    cameraDistance: 4.3
  },
  {
    id: 'tulips_and_carnations_in_a_vase',
    file: 'tulips_and_carnations_in_a_vase.glb',
    name: '郁金香与康乃馨瓶花',
    category: 'vase',
    categoryLabel: '瓶中繁花',
    tagline: '感恩与祝福交织',
    defaultMessage: '献上这一瓶温暖的感谢，祝你平安喜乐，顺遂无忧。',
    accentColor: '#f43f5e',
    glowColor: '#fecdd3',
    targetScale: 2.3,
    cameraDistance: 4.5
  },
  {
    id: 'zinnias_in_a_decorated_tile_vase',
    file: 'zinnias_in_a_decorated_tile_vase.glb',
    name: '彩釉花瓶百日菊',
    category: 'vase',
    categoryLabel: '瓶中繁花',
    tagline: '花期漫漫，长情相伴',
    defaultMessage: '愿友谊与爱如百日菊般恒久绵长，经得起岁月推敲。',
    accentColor: '#f59e0b',
    glowColor: '#fef08a',
    targetScale: 2.3,
    cameraDistance: 4.5
  },
  {
    id: 'magnolia_in_a_vase',
    file: 'magnolia_in_a_vase.glb',
    name: '瓷瓶木兰幽香',
    category: 'vase',
    categoryLabel: '瓶中繁花',
    tagline: '暗香浮动，高贵圣洁',
    defaultMessage: '如木兰幽香沁人心脾，愿你被世界温柔以待。',
    accentColor: '#fbcfe8',
    glowColor: '#fdf2f8',
    targetScale: 2.3,
    cameraDistance: 4.4
  },
  {
    id: 'flower_in_a_pot',
    file: 'flower_in_a_pot.glb',
    name: '素烧陶盆生机花',
    category: 'vase',
    categoryLabel: '瓶中繁花',
    tagline: '扎根沃土，欣欣向荣',
    defaultMessage: '扎根于平凡，盛开于热爱。愿你的每一步都坚实笃定。',
    accentColor: '#84cc16',
    glowColor: '#d9f99d',
    targetScale: 2.2,
    cameraDistance: 4.2
  },
  {
    id: 'wk8_potted_flowers_red_spider_lilies_attempt',
    file: 'wk8_potted_flowers_red_spider_lilies_attempt.glb',
    name: '盆栽红花石蒜',
    category: 'vase',
    categoryLabel: '瓶中繁花',
    tagline: '绯红似火，别样风骨',
    defaultMessage: '愿你拥有独特的风骨与不羁的灵魂，自信绽放。',
    accentColor: '#dc2626',
    glowColor: '#fca5a5',
    targetScale: 2.2,
    cameraDistance: 4.2
  },

  // ── 🪷 睡莲、荷花与百合 (Lotus & Lilies) ───────────────────
  {
    id: 'lotus_flower_by_geometry_nodes',
    file: 'lotus_flower_by_geometry_nodes.glb',
    name: '几何水韵青莲',
    category: 'lotus',
    categoryLabel: '水生莲花',
    tagline: '清波涟漪，出尘不染',
    defaultMessage: '愿你心如止水，清澈明朗，在喧嚣红尘中安然盛开。',
    accentColor: '#38bdf8',
    glowColor: '#bae6fd',
    targetScale: 2.5,
    cameraDistance: 4.5
  },
  {
    id: 'stylized_lotus_flower',
    file: 'stylized_lotus_flower.glb',
    name: '静心禅莲',
    category: 'lotus',
    categoryLabel: '水生莲花',
    tagline: '一花一世界，一叶一菩提',
    defaultMessage: '放下所有浮躁与焦虑，愿片刻的宁静为你注入新的力量。',
    accentColor: '#06b6d4',
    glowColor: '#cffafe',
    targetScale: 2.1,
    cameraDistance: 4.0
  },
  {
    id: 'pink_lotus_flower_cluster',
    file: 'pink_lotus_flower_cluster.glb',
    name: '盛夏粉荷丛',
    category: 'lotus',
    categoryLabel: '水生莲花',
    tagline: '荷风送香气，竹露滴清响',
    defaultMessage: '愿清凉的荷风吹散所有的烦闷，带来满心欢喜。',
    accentColor: '#ec4899',
    glowColor: '#fbcfe8',
    targetScale: 2.5,
    cameraDistance: 4.8
  },
  {
    id: 'ga_free_301_pink_lotus_twin_bloom',
    file: 'ga_free_301_pink_lotus_twin_bloom.glb',
    name: '并蒂粉莲',
    category: 'lotus',
    categoryLabel: '水生莲花',
    tagline: '同心并蒂，连理长春',
    defaultMessage: '愿情深似海，同心同德，携手漫步在岁月的花海中。',
    accentColor: '#f43f5e',
    glowColor: '#fecdd3',
    targetScale: 2.4,
    cameraDistance: 4.6
  },
  {
    id: 'ga_free_401_single_lotus_flower_cluster__tt',
    file: 'ga_free_401_single_lotus_flower_cluster__tt.glb',
    name: '幽谷清荷',
    category: 'lotus',
    categoryLabel: '水生莲花',
    tagline: '独立清波，自成一格',
    defaultMessage: '不随波逐流，愿你始终保持独立而清醒的自我。',
    accentColor: '#fb7185',
    glowColor: '#ffe4e6',
    targetScale: 2.4,
    cameraDistance: 4.6
  },
  {
    id: 'ga_free_851_ancient_white_lotus_flower_clustertt',
    file: 'ga_free_851_ancient_white_lotus_flower_clustertt.glb',
    name: '千年古白莲',
    category: 'lotus',
    categoryLabel: '水生莲花',
    tagline: '古韵悠长，圣洁无瑕',
    defaultMessage: '穿越千年时光的圣洁白莲，为你祈福安康吉祥。',
    accentColor: '#e0f2fe',
    glowColor: '#ffffff',
    targetScale: 2.4,
    cameraDistance: 4.6
  },
  {
    id: 'lily',
    file: 'lily.glb',
    name: '纯白百合',
    category: 'lotus',
    categoryLabel: '水生莲花',
    tagline: '百年好合，纯洁美好',
    defaultMessage: '百合花开，吉祥常伴。愿你拥有纯洁无瑕的快乐。',
    accentColor: '#f8fafc',
    glowColor: '#ffffff',
    targetScale: 2.2,
    cameraDistance: 4.0
  },
  {
    id: 'lilies',
    file: 'lilies.glb',
    name: '香水百合簇',
    category: 'lotus',
    categoryLabel: '水生莲花',
    tagline: '清香怡人，高雅大方',
    defaultMessage: '愿百合的幽香拂过你的眉梢，带给你无尽的安宁与喜悦。',
    accentColor: '#f1f5f9',
    glowColor: '#ffffff',
    targetScale: 2.3,
    cameraDistance: 4.2
  },
  {
    id: 'lily_flower',
    file: 'lily_flower.glb',
    name: '圣洁百合',
    category: 'lotus',
    categoryLabel: '水生莲花',
    tagline: '向光而立，洁白无瑕',
    defaultMessage: '愿你如百合般高洁自信，无畏风雨，从容盛开。',
    accentColor: '#e2e8f0',
    glowColor: '#ffffff',
    targetScale: 2.2,
    cameraDistance: 4.0
  },
  {
    id: 'cc0__red_spider_lily_lycoris_radiata',
    file: 'cc0__red_spider_lily_lycoris_radiata.glb',
    name: '彼岸红花石蒜',
    category: 'lotus',
    categoryLabel: '水生莲花',
    tagline: '生生相错，心念永随',
    defaultMessage: '跨越千山万水的挂念，愿我的思念能化作光芒温暖你。',
    accentColor: '#dc2626',
    glowColor: '#f87171',
    targetScale: 2.4,
    cameraDistance: 4.6
  },

  // ── 🌸 樱花、木兰与山茶 (Sakura & Camellias) ──────────────
  {
    id: 'sakura',
    file: 'sakura.glb',
    name: '早春落樱',
    category: 'sakura',
    categoryLabel: '樱花木兰',
    tagline: '落樱如雪，春光如诗',
    defaultMessage: '春樱盛开正是人间好时节，愿你与所有的美好不期而遇。',
    accentColor: '#f472b6',
    glowColor: '#fbcfe8',
    targetScale: 2.3,
    cameraDistance: 4.4
  },
  {
    id: 'cherry_tree',
    file: 'cherry_tree.glb',
    name: '盛开樱花树',
    category: 'sakura',
    categoryLabel: '樱花木兰',
    tagline: '一树繁花，倾城盛景',
    defaultMessage: '愿你的人生如这一树繁花，壮丽绚烂，生机盎然！',
    accentColor: '#f472b6',
    glowColor: '#fce7f3',
    targetScale: 2.6,
    cameraDistance: 5.2
  },
  {
    id: 'tree_sakura',
    file: 'tree_sakura.glb',
    name: '唯美樱花木',
    category: 'sakura',
    categoryLabel: '樱花木兰',
    tagline: '落英缤纷，诗意盎然',
    defaultMessage: '愿你在繁忙的奔波中，也能驻足欣赏一抹落樱的静美。',
    accentColor: '#ec4899',
    glowColor: '#fbcfe8',
    targetScale: 2.5,
    cameraDistance: 5.0
  },
  {
    id: 'sakura_tree_01_-_low_poly_model',
    file: 'sakura_tree_01_-_low_poly_model.glb',
    name: '极简棱镜樱花树',
    category: 'sakura',
    categoryLabel: '樱花木兰',
    tagline: '极简童话，春日微风',
    defaultMessage: '简单的快乐最纯粹，愿童话般的温暖常伴你身边。',
    accentColor: '#f472b6',
    glowColor: '#fce7f3',
    targetScale: 2.4,
    cameraDistance: 4.8
  },
  {
    id: 'updated____sakura_cherry_blossom_cc0',
    file: 'updated____sakura_cherry_blossom_cc0.glb',
    name: '春雪古风樱花',
    category: 'sakura',
    categoryLabel: '樱花木兰',
    tagline: '古风韵味，落樱缤纷',
    defaultMessage: '穿越时空的东方美学，将这一份典雅春光送予你。',
    accentColor: '#fb7185',
    glowColor: '#ffe4e6',
    targetScale: 2.5,
    cameraDistance: 5.0
  },
  {
    id: 'cc0__youko_sakura_prunus_yoko.glb',
    file: 'cc0__youko_sakura_prunus_yoko.glb',
    name: '阳春阳子樱',
    category: 'sakura',
    categoryLabel: '樱花木兰',
    tagline: '灿烂若霞，和平之愿',
    defaultMessage: '愿阳光驱散所有阴霾，和平与喜悦充盈你的每一天。',
    accentColor: '#ec4899',
    glowColor: '#fbcfe8',
    targetScale: 2.4,
    cameraDistance: 4.6
  },
  {
    id: 'cc0__japanese_apricot_prunus_mume',
    file: 'cc0__japanese_apricot_prunus_mume.glb',
    name: '傲骨寒梅',
    category: 'sakura',
    categoryLabel: '樱花木兰',
    tagline: '不经一番寒彻骨，怎得梅花扑鼻香',
    defaultMessage: '请相信自己的坚韧，经过风雪洗礼后的你更加璀璨夺目。',
    accentColor: '#e11d48',
    glowColor: '#fda4af',
    targetScale: 2.4,
    cameraDistance: 4.8
  },
  {
    id: 'cc0__lilytree_magnolia_denudata',
    file: 'cc0__lilytree_magnolia_denudata.glb',
    name: '白玉兰玉树',
    category: 'sakura',
    categoryLabel: '樱花木兰',
    tagline: '霓裳片片，玉树临风',
    defaultMessage: '愿你气质如兰，高洁优雅，不染世俗纤尘。',
    accentColor: '#f8fafc',
    glowColor: '#ffffff',
    targetScale: 2.5,
    cameraDistance: 4.8
  },
  {
    id: 'cc0____sasanqua_camellia_sasanqua',
    file: 'cc0____sasanqua_camellia_sasanqua.glb',
    name: '粉白茶梅',
    category: 'sakura',
    categoryLabel: '樱花木兰',
    tagline: '寒冬送暖，清雅从容',
    defaultMessage: '在最寒冷的季节里依旧温暖盛开，愿你充满前行的勇气。',
    accentColor: '#f472b6',
    glowColor: '#fce7f3',
    targetScale: 2.4,
    cameraDistance: 4.6
  },
  {
    id: 'cc0____sasanqua_red_c._sasanqua',
    file: 'cc0____sasanqua_red_c._sasanqua.glb',
    name: '丹红山茶',
    category: 'sakura',
    categoryLabel: '樱花木兰',
    tagline: '谦逊美德，理想之爱',
    defaultMessage: '沉静谦逊却又无比坚定，愿你收获心中理想的爱与幸福。',
    accentColor: '#dc2626',
    glowColor: '#f87171',
    targetScale: 2.4,
    cameraDistance: 4.6
  },
  {
    id: 'cc0__camellia_sasanqua_shishigashira',
    file: 'cc0__camellia_sasanqua_shishigashira.glb',
    name: '狮子头红茶梅',
    category: 'sakura',
    categoryLabel: '樱花木兰',
    tagline: '华贵重瓣，热烈奔放',
    defaultMessage: '重瓣繁花盛放如烈火，愿你的人生充实热烈，毫无遗憾。',
    accentColor: '#b91c1c',
    glowColor: '#fca5a5',
    targetScale: 2.4,
    cameraDistance: 4.6
  },
  {
    id: 'cc0__satsuki_azalea_rhododendron_indicum',
    file: 'cc0__satsuki_azalea_rhododendron_indicum.glb',
    name: '五月杜鹃花',
    category: 'sakura',
    categoryLabel: '樱花木兰',
    tagline: '繁花似海，爱的喜悦',
    defaultMessage: '愿满山的杜鹃花为你带来久违的欢欣与雀跃。',
    accentColor: '#e11d48',
    glowColor: '#fda4af',
    targetScale: 2.4,
    cameraDistance: 4.8
  },
  {
    id: 'cc0__japanese_weigela_w._japonica',
    file: 'cc0__japanese_weigela_w._japonica.glb',
    name: '绚丽锦带花',
    category: 'sakura',
    categoryLabel: '樱花木兰',
    tagline: '如锦如带，前程似锦',
    defaultMessage: '祝你前程似锦，繁花相拥，一切努力皆有回响。',
    accentColor: '#db2777',
    glowColor: '#f472b6',
    targetScale: 2.4,
    cameraDistance: 4.6
  },

  // ── 🌺 牡丹、兰花与名花 (Peonies & Orchids) ────────────────
  {
    id: 'peony_flowers',
    file: 'peony_flowers.glb',
    name: '国色天香牡丹簇',
    category: 'peony',
    categoryLabel: '名贵花卉',
    tagline: '国色天香，富贵吉祥',
    defaultMessage: '唯有牡丹真国色，花开时节动京城。愿你富贵安康，诸事顺遂！',
    accentColor: '#db2777',
    glowColor: '#fbcfe8',
    targetScale: 2.5,
    cameraDistance: 4.8
  },
  {
    id: 'pink_peony',
    file: 'pink_peony.glb',
    name: '娇粉富贵牡丹',
    category: 'peony',
    categoryLabel: '名贵花卉',
    tagline: '雍容华贵，倾国倾城',
    defaultMessage: '愿你拥有雍容大度的胸怀与富足安宁的生活。',
    accentColor: '#ec4899',
    glowColor: '#fce7f3',
    targetScale: 2.5,
    cameraDistance: 4.8
  },
  {
    id: 'orchid_flower',
    file: 'orchid_flower.glb',
    name: '高洁空谷幽兰',
    category: 'peony',
    categoryLabel: '名贵花卉',
    tagline: '空谷幽兰，自成芳华',
    defaultMessage: '愿你保有内心的澄澈与从容，不争喧嚣，自得芳华。',
    accentColor: '#c084fc',
    glowColor: '#f3e8ff',
    targetScale: 2.4,
    cameraDistance: 4.6
  },
  {
    id: 'margarita_flower',
    file: 'margarita_flower.glb',
    name: '阳光雏菊',
    category: 'peony',
    categoryLabel: '名贵花卉',
    tagline: '纯真烂漫，向阳而生',
    defaultMessage: '像雏菊一样简单快乐，勇敢地迎着光的方向奔跑吧！',
    accentColor: '#eab308',
    glowColor: '#fef08a',
    targetScale: 2.2,
    cameraDistance: 3.8
  },
  {
    id: 'single_flower__carnation_pink',
    file: 'single_flower__carnation_pink.glb',
    name: '慈爱粉康乃馨',
    category: 'peony',
    categoryLabel: '名贵花卉',
    tagline: '温馨慈爱，感恩于心',
    defaultMessage: '一朵康乃馨寄托深深谢意，愿亲爱的人健康平安，笑口常开。',
    accentColor: '#f43f5e',
    glowColor: '#fecdd3',
    targetScale: 2.2,
    cameraDistance: 4.0
  },
  {
    id: 'blooming_hibiscus_time-lapse_animation',
    file: 'blooming_hibiscus_time-lapse_animation.glb',
    name: '时光绽放木槿花',
    category: 'peony',
    categoryLabel: '名贵花卉',
    tagline: '历经时光，愈发美丽',
    defaultMessage: '木槿朝开暮落却生生不息，愿你历经千帆依然充满生机。',
    accentColor: '#fb7185',
    glowColor: '#ffe4e6',
    targetScale: 2.3,
    cameraDistance: 4.2
  },
  {
    id: 'generic_narcissus_flower',
    file: 'generic_narcissus_flower.glb',
    name: '凌波仙子水仙',
    category: 'peony',
    categoryLabel: '名贵花卉',
    tagline: '万事如意，吉祥迎春',
    defaultMessage: '水仙报喜，岁岁安康。愿新的一年吉祥如意，好运连连。',
    accentColor: '#fef08a',
    glowColor: '#fef9c3',
    targetScale: 2.1,
    cameraDistance: 3.8
  },
  {
    id: 'orange_flowers_-_calendula',
    file: 'orange_flowers_-_calendula.glb',
    name: '金盏花暖阳',
    category: 'peony',
    categoryLabel: '名贵花卉',
    tagline: '疗愈心灵，满载希望',
    defaultMessage: '金盏花的阳光抚平疲惫，愿你重获满满元气。',
    accentColor: '#f97316',
    glowColor: '#fed7aa',
    targetScale: 2.2,
    cameraDistance: 4.0
  },
  {
    id: 'flower_-_armeria_maritima',
    file: 'flower_-_armeria_maritima.glb',
    name: '海石竹小球花',
    category: 'peony',
    categoryLabel: '名贵花卉',
    tagline: '深情同情，守护相伴',
    defaultMessage: '愿我小小的守护能成为你前行路上坚实的后盾。',
    accentColor: '#ec4899',
    glowColor: '#fbcfe8',
    targetScale: 2.1,
    cameraDistance: 3.8
  },
  {
    id: 'cc0__montbretia_c._x_crocosmiiflora',
    file: 'cc0__montbretia_c._x_crocosmiiflora.glb',
    name: '雄黄兰火星花',
    category: 'peony',
    categoryLabel: '名贵花卉',
    tagline: '热情洋溢，活力无限',
    defaultMessage: '愿你始终拥有燃烧的热情，勇敢去爱，去生活！',
    accentColor: '#ea580c',
    glowColor: '#ffedd5',
    targetScale: 2.3,
    cameraDistance: 4.4
  },
  {
    id: 'cc0__hirsute_raspberry_rubus_hirsutus',
    file: 'cc0__hirsute_raspberry_rubus_hirsutus.glb',
    name: '野草莓白花',
    category: 'peony',
    categoryLabel: '名贵花卉',
    tagline: '自然质朴，甜蜜期盼',
    defaultMessage: '每一次微小的开花都会结出甘甜的果实，期待你的丰收。',
    accentColor: '#10b981',
    glowColor: '#d1fae5',
    targetScale: 2.3,
    cameraDistance: 4.4
  },
  {
    id: 'cc0__dead-nettle_l._album_var._barbatum',
    file: 'cc0__dead-nettle_l._album_var._barbatum.glb',
    name: '野芝麻白华',
    category: 'peony',
    categoryLabel: '名贵花卉',
    tagline: '坚韧不拔，默默绽放',
    defaultMessage: '无需他人评说，默默积蓄力量，终将绽放属于你的光芒。',
    accentColor: '#059669',
    glowColor: '#a7f3d0',
    targetScale: 2.3,
    cameraDistance: 4.4
  },

  // ── ✨ 奇幻、生机与趣味 (Fantasy & Life) ───────────────────
  {
    id: 'alien_flower',
    file: 'alien_flower.glb',
    name: '异星奇幻花',
    category: 'fantasy',
    categoryLabel: '奇幻生机',
    tagline: '浩瀚宇宙，独一无二',
    defaultMessage: '你不需要迎合这世界的标准，你的特别就是最珍贵的存在。',
    accentColor: '#14b8a6',
    glowColor: '#99f6e4',
    targetScale: 2.3,
    cameraDistance: 4.4
  },
  {
    id: 'alien_flowers',
    file: 'alien_flowers.glb',
    name: '星际繁花丛',
    category: 'fantasy',
    categoryLabel: '奇幻生机',
    tagline: '漫步星河，梦幻漫游',
    defaultMessage: '带你穿梭宇宙的星尘与花海，愿你的梦境无比广阔奇妙。',
    accentColor: '#06b6d4',
    glowColor: '#a5f3fc',
    targetScale: 2.4,
    cameraDistance: 4.6
  },
  {
    id: 'blue_flower_animated',
    file: 'blue_flower_animated.glb',
    name: '灵动幻蓝花',
    category: 'fantasy',
    categoryLabel: '奇幻生机',
    tagline: '呼吸律动，灵动生息',
    defaultMessage: '随微风轻轻摇曳，愿你的每一天都轻盈愉悦。',
    accentColor: '#2563eb',
    glowColor: '#93c5fd',
    targetScale: 2.2,
    cameraDistance: 4.0
  },
  {
    id: 'simple_flower_loop',
    file: 'simple_flower_loop.glb',
    name: '律动生机花',
    category: 'fantasy',
    categoryLabel: '奇幻生机',
    tagline: '每一次呼吸，都在萌发新生',
    defaultMessage: '生命不息，希望常在。愿每一次律动都带给你坚定的力量。',
    accentColor: '#10b981',
    glowColor: '#a7f3d0',
    targetScale: 2.1,
    cameraDistance: 4.0
  },
  {
    id: 'colored_flower',
    file: 'colored_flower.glb',
    name: '幻彩霓裳花',
    category: 'fantasy',
    categoryLabel: '奇幻生机',
    tagline: '灵感如光，色彩斑斓',
    defaultMessage: '愿你的生活拥有无限色彩，每一刻都如烟火般璀璨。',
    accentColor: '#8b5cf6',
    glowColor: '#ddd6fe',
    targetScale: 2.2,
    cameraDistance: 4.0
  },
  {
    id: 'sunfire_tropic_-_flowers',
    file: 'sunfire_tropic_-_flowers.glb',
    name: '热带烈焰花',
    category: 'fantasy',
    categoryLabel: '奇幻生机',
    tagline: '热烈奔放，生命赞歌',
    defaultMessage: '热烈地去爱、去探索，愿你永远充满无尽的探索欲与活力。',
    accentColor: '#f97316',
    glowColor: '#fed7aa',
    targetScale: 2.5,
    cameraDistance: 4.8
  },
  {
    id: 'garden_whim_-_flowers',
    file: 'garden_whim_-_flowers.glb',
    name: '梦境花园繁花',
    category: 'fantasy',
    categoryLabel: '奇幻生机',
    tagline: '微风吹拂，绮梦初醒',
    defaultMessage: '步入这片属于你的奇妙花园，愿所有心愿皆能温柔实现。',
    accentColor: '#ec4899',
    glowColor: '#fbcfe8',
    targetScale: 2.5,
    cameraDistance: 5.0
  },
  {
    id: 'flowers_pointcloud',
    file: 'flowers_pointcloud.glb',
    name: '全息粒子花海',
    category: 'fantasy',
    categoryLabel: '奇幻生机',
    tagline: '星尘聚散，光影流动',
    defaultMessage: '粒子汇聚成璀璨星河，愿这束光点亮你心中的每一个梦想。',
    accentColor: '#38bdf8',
    glowColor: '#bae6fd',
    targetScale: 2.5,
    cameraDistance: 5.0
  },
  {
    id: 'flower_-_cartoon_style',
    file: 'flower_-_cartoon_style.glb',
    name: '治愈小童趣',
    category: 'fantasy',
    categoryLabel: '奇幻生机',
    tagline: '保持可爱，奔赴热爱',
    defaultMessage: '愿你历经千帆，归来仍葆有一颗纯真治愈的童心。',
    accentColor: '#fb923c',
    glowColor: '#ffedd5',
    targetScale: 2.0,
    cameraDistance: 3.8
  },
  {
    id: 'low_poly_purple_flowers',
    file: 'low_poly_purple_flowers.glb',
    name: '紫夜星芒花',
    category: 'fantasy',
    categoryLabel: '奇幻生机',
    tagline: '夜色深邃，星芒闪烁',
    defaultMessage: '即使身处暗夜，也请记得你本身就是一颗发光的星辰。',
    accentColor: '#7c3aed',
    glowColor: '#c4b5fd',
    targetScale: 2.1,
    cameraDistance: 4.0
  },
  {
    id: 'flowers_lowpoly',
    file: 'flowers_lowpoly.glb',
    name: '极简棱镜花',
    category: 'fantasy',
    categoryLabel: '奇幻生机',
    tagline: '极简纯粹，棱角分明',
    defaultMessage: '做纯粹的自己，在简素的时光里绽放最清晰的棱角。',
    accentColor: '#059669',
    glowColor: '#6ee7b7',
    targetScale: 2.1,
    cameraDistance: 3.8
  },
  {
    id: 'anemone_flower_low_poly',
    file: 'anemone_flower_low_poly.glb',
    name: '微风银莲花',
    category: 'fantasy',
    categoryLabel: '奇幻生机',
    tagline: '微风知我意，寄语送思念',
    defaultMessage: '跨越山海与时光，将这一份轻柔的牵挂送至你手心。',
    accentColor: '#3b82f6',
    glowColor: '#93c5fd',
    targetScale: 2.2,
    cameraDistance: 4.0
  },
  {
    id: 'flower_test',
    file: 'flower_test.glb',
    name: '初见晨露花',
    category: 'fantasy',
    categoryLabel: '奇幻生机',
    tagline: '人生若只如初见',
    defaultMessage: '感谢每一次美好的相遇，愿初见时的温暖长留心底。',
    accentColor: '#e11d48',
    glowColor: '#fecdd3',
    targetScale: 2.1,
    cameraDistance: 3.8
  },
  {
    id: '235_flower',
    file: '235_flower.glb',
    name: '清新野雏菊',
    category: 'fantasy',
    categoryLabel: '奇幻生机',
    tagline: '自由生长，随遇而安',
    defaultMessage: '在微风中自由摇曳，愿你拥有随遇而安的豁达与快乐。',
    accentColor: '#eab308',
    glowColor: '#fef08a',
    targetScale: 2.1,
    cameraDistance: 3.8
  },
  {
    id: '896507260fd547758928e6e850c30cb1',
    file: '896507260fd547758928e6e850c30cb1.glb',
    name: '灵动晨光花',
    category: 'fantasy',
    categoryLabel: '奇幻生机',
    tagline: '破晓之光，生命初醒',
    defaultMessage: '愿第一缕晨光驱散困扰，带给你全新一天的希望。',
    accentColor: '#06b6d4',
    glowColor: '#cffafe',
    targetScale: 2.1,
    cameraDistance: 3.8
  },
  {
    id: '8992b6b94b094a069930104a32d5e9f5',
    file: '8992b6b94b094a069930104a32d5e9f5.glb',
    name: '优雅幽境花',
    category: 'fantasy',
    categoryLabel: '奇幻生机',
    tagline: '幽深静谧，独享清欢',
    defaultMessage: '愿你在自己的小小世界里，独享这份清欢与自由。',
    accentColor: '#a855f7',
    glowColor: '#f3e8ff',
    targetScale: 2.3,
    cameraDistance: 4.4
  },
  {
    id: 'b3b0aa33f8484bd3b003c2902399c7ac',
    file: 'b3b0aa33f8484bd3b003c2902399c7ac.glb',
    name: '清润玉露花',
    category: 'fantasy',
    categoryLabel: '奇幻生机',
    tagline: '玉露晶莹，滋润心田',
    defaultMessage: '愿温柔的关怀如甘霖玉露，悄然滋润你的心田。',
    accentColor: '#38bdf8',
    glowColor: '#bae6fd',
    targetScale: 2.1,
    cameraDistance: 3.8
  },
  {
    id: 'flower_grand',
    file: 'flower_grand.glb',
    name: '盛大华彩花',
    category: 'fantasy',
    categoryLabel: '奇幻生机',
    tagline: '繁花满堂，璀璨夺目',
    defaultMessage: '祝贺每一个闪光的成就，愿你继续乘风破浪，光芒万丈！',
    accentColor: '#f43f5e',
    glowColor: '#fda4af',
    targetScale: 2.4,
    cameraDistance: 4.6
  },
  {
    id: 'flower_vivid',
    file: 'flower_vivid.glb',
    name: '明媚生机花',
    category: 'fantasy',
    categoryLabel: '奇幻生机',
    tagline: '明媚动人，生机勃发',
    defaultMessage: '愿你的笑容永远明媚如初，照亮身边的每一个人。',
    accentColor: '#fb923c',
    glowColor: '#ffedd5',
    targetScale: 2.2,
    cameraDistance: 4.0
  },
  {
    id: 'flower_delicate',
    file: 'flower_delicate.glb',
    name: '柔美初绽花',
    category: 'fantasy',
    categoryLabel: '奇幻生机',
    tagline: '轻柔细腻，温暖守护',
    defaultMessage: '愿世间所有温柔都向你倾斜，祝你天天开心。',
    accentColor: '#f472b6',
    glowColor: '#fdf2f8',
    targetScale: 2.1,
    cameraDistance: 3.8
  },
  {
    id: 'flowers_lush',
    file: 'flowers_lush.glb',
    name: '繁盛花海丛',
    category: 'fantasy',
    categoryLabel: '奇幻生机',
    tagline: '簇拥相依，温暖同行',
    defaultMessage: '很高兴能与你在这繁华世间相遇同行，感谢一路有你！',
    accentColor: '#8b5cf6',
    glowColor: '#ede9fe',
    targetScale: 2.4,
    cameraDistance: 4.8
  },
  {
    id: 'flowers_mini',
    file: 'flowers_mini.glb',
    name: '微风小花丛',
    category: 'fantasy',
    categoryLabel: '奇幻生机',
    tagline: '微小而坚韧，点滴皆欢喜',
    defaultMessage: '收集生活中微小的确幸，愿你的日子闪闪发光。',
    accentColor: '#10b981',
    glowColor: '#d1fae5',
    targetScale: 2.1,
    cameraDistance: 3.8
  },
  {
    id: 'flowers_sunny',
    file: 'flowers_sunny.glb',
    name: '暖阳灿烂花',
    category: 'fantasy',
    categoryLabel: '奇幻生机',
    tagline: '暖阳融融，生机盎然',
    defaultMessage: '愿阳光穿透阴霾，温暖照进你的心里。',
    accentColor: '#f59e0b',
    glowColor: '#fef08a',
    targetScale: 2.2,
    cameraDistance: 4.0
  },
  {
    id: 'flowers_radiant',
    file: 'flowers_radiant.glb',
    name: '光芒四射花',
    category: 'fantasy',
    categoryLabel: '奇幻生机',
    tagline: '自带光芒，自信绽放',
    defaultMessage: '勇敢做自己，你本身就是一道最美丽的风景。',
    accentColor: '#ec4899',
    glowColor: '#fbcfe8',
    targetScale: 2.3,
    cameraDistance: 4.4
  },
  {
    id: 'flowers',
    file: 'flowers.glb',
    name: '蔚蓝花卉组',
    category: 'fantasy',
    categoryLabel: '奇幻生机',
    tagline: '生机盎然，蔚为壮观',
    defaultMessage: '愿你的每一天都充满蓬勃的生命力与意想不到的惊喜。',
    accentColor: '#0ea5e9',
    glowColor: '#7dd3fc',
    targetScale: 2.4,
    cameraDistance: 4.8
  },
  {
    id: 'red_flowers',
    file: 'red_flowers.glb',
    name: '炽热绯红花',
    category: 'fantasy',
    categoryLabel: '奇幻生机',
    tagline: '如火如荼，激情盛开',
    defaultMessage: '愿你对生活永远保有最初的炽热与激情！',
    accentColor: '#dc2626',
    glowColor: '#f87171',
    targetScale: 2.2,
    cameraDistance: 4.2
  }
];

export const DEFAULT_MODEL_ID = 'bouquet';

export function getFlowerModelById(id?: string): FlowerModelInfo {
  if (!id) return FLOWER_MODELS[0];
  const found = FLOWER_MODELS.find((m) => m.id === id || m.file.replace('.glb', '') === id);
  return found || FLOWER_MODELS[0];
}

export function getRandomFlowerModel(excludeId?: string): FlowerModelInfo {
  const pool = excludeId ? FLOWER_MODELS.filter((m) => m.id !== excludeId) : FLOWER_MODELS;
  const randomIndex = Math.floor(Math.random() * pool.length);
  return pool[randomIndex] || FLOWER_MODELS[0];
}
